### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jaanjah** [PulsarcGame/Pulserv#1]
Going to do a code review as an issue since can't create comments on commits.

## Root project
- Ignore the output directory in `.gitignore` - Also I think you can remove `*.js`, because the compiled javascript will all be in output directory anyway.
https://github.com/PulsarcGame/Pulserv/blob/master/tsconfig.json#L15
- Add `package.json`, you have `package-lock.json`, but you need `package.json` for npm to get the required dependencies, you can create one easily by doing `npm init -y`
- Add CONTRIBUTING.md with how to run the server
- Use `.env` files instead of `pulsarv.json`
- Usually code files go under `src/` directory.

## Code itself
- Do not use raw queries! Seriously, big threat to SQL injection. You should use some SQL Query Builder instead (My company uses Knex (has typescript support)).
- use `export default` if you are only exporting 1 thing in a file, `import Map from './map'` vs `import { Map } from './map'`

## Ideas/Tips to do
These are not necessary, but when used correctly are really useful.
- Use code linting, you can use TSLint, but I think ESLint also added TypeScript support lately - linters keep your code clean and makes sure that the code base has the same coding style (you can use some recommended airbnb or something for coding style rules)
- Add testing, these are always useful, you can use Jest for testing, this makes sure that the code works as it's supposed to.
- Add docker support - Using `docker-compose up` would make development really easy if you have to setup some external services for the code to work.

I understand this repo is very new and WIP, but I just wanted to do this :)

**Comment by Adrriii** [comment]
Thanks for that :)
